--huh? this file doesn't seem to exist in lonn...
--Loenn/entities/world_panel.lua [PrismaticHelper]: Rysy.LuaSupport.LuaException: [string "new_require"]:10: module 'utils.depths' not found:
return {}