using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CA1812:Avoid uninstantiated internal classes", Justification = "Assembly scanning for entities uses these", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1008:Enums should have zero value", Justification = "Doesn't make sense", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1303:Do not pass literals as localized parameters", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA2007:Consider using ConfigureAwait", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1034:Nested types should not be visible", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be readonly", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1002:Do not expose generic lists", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1003:Use generic event handler instances", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1051:Do not declare visible instance fields", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1032:Implement standard Exception constructors", Justification = "Not all exceptions should be publically constructable", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1814:Prefer jagged arrays over multidimensional", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1065:Do not raise exceptions in unexpected places", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1720:Identifier contains type name", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1815:Override equals operator on value types", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1822:Mark members as static", Justification = "Doesn't make sense all the time", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA2002:Do not lock on objects with weak identity", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1805:Do not initialize unnecessarily", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1508:Avoid dead conditional code", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1710:Identifiers should have correct suffix", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1308:Normalize strings to uppercase", Justification = "Sprite paths use lowercase", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA5392:Use DefaultDllImportSearchPaths", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1819:Properties should not return arrays", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1031:Do not catch general exception types", Justification = "Many places need to catch any exception to not crash the program", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1707:Identifiers should not contain underscores", Justification = "", Scope = "module")]

[assembly: SuppressMessage("Usage", "CA1062:Validate arguments of public members", Justification = "todo", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "annoying, should be done at some point though", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1721:Property names should not match get methods", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1724:Type names should not match namespaces", Justification = "", Scope = "module")]

[assembly: SuppressMessage("Usage", "CA1515", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1711:Do not end types with 'Collection'", Justification = "why", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1024:Use properties where appropriate", Justification = "way too agressive", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1033", Justification = "", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA5394:Random is an insecure rng", Justification = "Don't need crypto-safe rng", Scope = "module")]
[assembly: SuppressMessage("Usage", "CA1859:Change return type of method to concrete type", Justification = "Triggers in many irrelevant places (like where they would get boxed immediately anyway)", Scope = "module")]