<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!--<DebugSymbols>true</DebugSymbols>-->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <FNA Condition="'$(FNA)' == ''">FNA</FNA>
    <SourceCodePlugins Condition="'$(SourceCodePlugins)' == ''">SourceCodePlugins</SourceCodePlugins>
    <DefineConstants Condition="'$(FNA)' != ''">$(DefineConstants);FNA</DefineConstants>
    <DefineConstants Condition="'$(SourceCodePlugins)' != ''">$(DefineConstants);SourceCodePlugins</DefineConstants>
    <ApplicationManifest>Rysy.manifest</ApplicationManifest>
  </PropertyGroup>
    
    <!-- Nuget package -->
    <PropertyGroup>
        <PackageId>Rysy</PackageId>
        <PackageDescription>A map editor for Celeste.</PackageDescription>
        <Version>0.0.14</Version>
        <Authors>JaThePlayer</Authors>
        <Copyright>Copyright $([System.DateTime]::Now.ToString(yyyy)) $(Authors)</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>Celeste;CelesteRysy</PackageTags>
        <PackageProjectUrl>https://github.com/JaThePlayer/Rysy</PackageProjectUrl>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="$(SolutionDir)/README.md" PackagePath="README.md" Visible="false" />
    </ItemGroup>

  <PropertyGroup>
  <!--
    <AnalysisMode>All</AnalysisMode>
    <WarningsAsErrors>$(WarningsAsErrors);CA1307;CA1309;CA1310;CA1305;CA1311</WarningsAsErrors>
  -->
  </PropertyGroup>

  <PropertyGroup Condition="'$(FNA)' != ''">
    <_IsWindows Condition="'$(RuntimeIdentifier)' == 'win-x64'">true</_IsWindows>
    <_IsLinux Condition="'$(RuntimeIdentifier)' == 'linux-x64'">true</_IsLinux>
    <_IsMacOS_x64 Condition="'$(RuntimeIdentifier)' == 'osx-x64'">true</_IsMacOS_x64>
    <_IsMacOS_arm64 Condition="'$(RuntimeIdentifier)' == 'osx-arm64'">true</_IsMacOS_arm64>
    <_IsMacOS Condition="'$(_IsMacOS_x64)' != '' Or '$(_IsMacOS_arm64)' != ''">true</_IsMacOS>
    <_AnyOSTargetFound Condition=" '$(_IsWindows)' != '' Or '$(_IsMacOS)' != '' Or '$(_IsLinux)' != ''">true</_AnyOSTargetFound>
    
    <_IsWindows Condition=" '$(_AnyOSTargetFound)' == '' And '$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</_IsWindows>
    <_IsLinux Condition=" '$(_AnyOSTargetFound)' == '' And '$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</_IsLinux>
    <_IsMacOS Condition=" '$(_AnyOSTargetFound)' == '' And '$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">true</_IsMacOS>
    <_IsMacOS_x64 Condition=" '$(_AnyOSTargetFound)' == '' And '$(_IsMacOS)' == 'true' And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == '$([System.Runtime.InteropServices.Architecture]::X64)'">true</_IsMacOS_x64>
    <_IsMacOS_arm64 Condition=" '$(_AnyOSTargetFound)' == '' And '$(_IsMacOS)' == 'true' And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == '$([System.Runtime.InteropServices.Architecture]::Arm64)'">true</_IsMacOS_arm64>
      
    <_NativeRuntime Condition=" '$(_NativeRuntime)' == '' And '$(_IsMacOS_x64)' == 'true'">osx-x64</_NativeRuntime>
    <_NativeRuntime Condition=" '$(_NativeRuntime)' == '' And '$(_IsMacOS_arm64)' == 'true'">osx-arm64</_NativeRuntime>
    <_NativeRuntime Condition=" '$(_NativeRuntime)' == '' And '$(_IsLinux)' == 'true' And ('$(Prefer32Bit)' == 'false' Or '$(PlatformTarget)' == 'x64')">linux-x64</_NativeRuntime>
    <_NativeRuntime Condition=" '$(_NativeRuntime)' == '' And '$(_IsWindows)' == 'true' And ('$(Prefer32Bit)' == 'false' Or '$(PlatformTarget)' == 'x64')">win-x64</_NativeRuntime>

    <_NativeRuntimeCrossArch Condition="'$(_NativeRuntimeCrossArch)' == '' And '$(_IsMacOS)' == ''">$(_NativeRuntime)</_NativeRuntimeCrossArch>
    <_NativeRuntimeCrossArch Condition="'$(_NativeRuntimeCrossArch)' == '' And '$(_IsMacOS)' == 'true'">osx-universal</_NativeRuntimeCrossArch>
      
    <_NativeLibExt Condition="'$(_NativeRuntime)' == 'win-x64'">dll</_NativeLibExt>
    <_NativeLibExt Condition="'$(_NativeRuntime)' == 'osx-x64'">dylib</_NativeLibExt>
    <_NativeLibExt Condition="'$(_NativeRuntime)' == 'osx-arm64'">dylib</_NativeLibExt>
    <_NativeLibExt Condition="'$(_NativeRuntime)' == 'linux-x64'">so</_NativeLibExt>

    <_NativeExeExt Condition="'$(_NativeRuntime)' == 'win-x64'">.exe</_NativeExeExt>
    <!-- Not needed, as empty is the default
    <_NativeExeExt Condition="'$(_NativeRuntime)' == 'osx'"></_NativeExeExt>
    <_NativeExeExt Condition="'$(_NativeRuntime)' == 'linux-x64'"></_NativeExeExt>
    -->
  </PropertyGroup>
  
  <Target Name="ValidateOS" BeforeTargets="CoreCompile">
       <Error
              Text="This target is not supported. Available: win-x64, linux-x64, osx-x64, osx-arm64."
              Condition="'$(_NativeRuntime)' == ''" />
  </Target>

  <ItemGroup Condition="'$(FNA)' != ''">
      <Reference Include="FNA.dll">
          <HintPath>lib\FNA.dll</HintPath>
      </Reference>
      <!-- Include FNA in the nuget package for easier usage in mod plugins. -->
      <Content Include="lib\FNA.dll">
          <Pack>true</Pack>
          <PackagePath>lib\$(TargetFramework)</PackagePath>
      </Content>
    
    <Content Condition="'$(_NativeRuntime)' != ''" Include="runtimes\$(_NativeRuntimeCrossArch)\native\SDL3.$(_NativeLibExt)">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>False</Visible>
      <Pack>false</Pack>
    </Content>
    <Content Condition="'$(_NativeRuntime)' != ''" Include="runtimes\$(_NativeRuntimeCrossArch)\native\FAudio.$(_NativeLibExt)">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>False</Visible>
      <Pack>false</Pack>
    </Content>
    <Content Condition="'$(_NativeRuntime)' != ''" Include="runtimes\$(_NativeRuntimeCrossArch)\native\FNA3D.$(_NativeLibExt)">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>False</Visible>
      <Pack>false</Pack>
    </Content>
    <Content Condition="'$(_NativeRuntime)' != ''" Include="runtimes\$(_NativeRuntimeCrossArch)\native\libtheorafile.$(_NativeLibExt)">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>False</Visible>
      <Pack>false</Pack>
    </Content>
    <Content Condition="'$(_NativeRuntime)' != ''" Include="runtimes\$(_NativeRuntimeCrossArch)\native\lua51.$(_NativeLibExt)">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>False</Visible>
      <Pack>false</Pack>
    </Content>
  </ItemGroup>

  <!-- Set up a Piton Apphost if wanted -->
  <PropertyGroup>
    <CustomAppHost Condition="'$(_IsPublishing)' == 'true'">true</CustomAppHost>
  </PropertyGroup>
  <PropertyGroup Condition="'$(CustomAppHost)' != ''">
      <UseAppHost Condition="">false</UseAppHost>
  </PropertyGroup>
  <ItemGroup Condition="'$(CustomAppHost)' != ''">
      <Content Include="piton-runtime.yaml" TargetPath="piton-runtime.yaml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <Target Name="IncludeAppHosts" AfterTargets="CoreCompile" Condition="'$(CustomAppHost)' != ''">
      <ItemGroup>
          <Content Condition="'$(_NativeRuntime)' != ''" Include="runtimes\$(_NativeRuntime)\native\piton$(_NativeExeExt)">
              <Link>%(Filename)%(Extension)</Link>
              <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
              <Visible>False</Visible>
          </Content>
      </ItemGroup>
  </Target>
  <Target Name="BindAppHosts" AfterTargets="CoreCompile" DependsOnTargets="IncludeAppHosts" Outputs="$(OutputPath)\Rysy$(_NativeExeExt)" Condition="'$(CustomAppHost)' != ''" >
        <Message Importance="High" Text="Binding AppHost..." />

        <CreateAppHost AppHostSourcePath="runtimes\$(_NativeRuntime)\native\piton$(_NativeExeExt)"
                       AppHostDestinationPath="$(OutputPath)\Rysy$(_NativeExeExt)"
                       AppBinaryName="$(AssemblyName)$(TargetExt)" 
                       IntermediateAssembly="@(IntermediateAssembly->'%(FullPath)')"
                       WindowsGraphicalUserInterface="false"
        />
  </Target>
  <!-- The executable generated via CreateAppHost does not get auto-copied to the publish/ directory, we need to do this manually -->
  <Target Name="CopyExecutableToPublish" AfterTargets="PrepareForPublish" DependsOnTargets="BindAppHosts" Condition="'$(CustomAppHost)' != ''">
        <Copy SourceFiles="$(OutputPath)\Rysy$(_NativeExeExt)" DestinationFolder="$(PublishDir)" />
  </Target>

  <PropertyGroup>
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>
    
    
  <ItemGroup>
    <PackageReference Include="Hexa.NET.ImGui" Version="2.2.10-prerelease" />
    <PackageReference Include="Hjg.Pngcs" Version="1.1.5" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
    <PackageReference Include="Markdig" Version="0.43.0" />
    <PackageReference Include="NativeFileDialogSharp" Version="0.6.0-alpha" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(SourceCodePlugins)' != ''">
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Graphics\tilesets\subfolder\" />
  </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Rysy.Shared\Rysy.Shared.csproj" />
    </ItemGroup>
<!--    
    <PropertyGroup>
        <ApplicationIcon>Assets/Icon/icon.ico</ApplicationIcon>
    </PropertyGroup>
    -->
</Project>
