<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <InvariantGlobalization>true</InvariantGlobalization>
        <OptimizationPreference>Size</OptimizationPreference>
        <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
        <StackTraceSupport>false</StackTraceSupport>
        <UseAppHost>false</UseAppHost>
    </PropertyGroup>

</Project>
