name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build with .NET Core
      run: dotnet build "/p:Configuration=Release"

    - name: Upload universal artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Rysy
        path: Rysy/bin/Release/net7.0

    - name: Create Zip for release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        directory: 'Rysy/bin/Release/net7.0'
        filename: 'Rysy.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Rysy.zip"
