name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build with .NET Core
      run: |
        dotnet publish -c "Release" -r win-x64 --no-self-contained
        dotnet publish -c "Release" -r linux-x64 --no-self-contained
        dotnet publish -c "Release" -r osx-x64 --no-self-contained
      
    - name: Create release folders
      working-directory: ./Rysy/bin/Release/net7.0
      run: |
        echo "Preparing build dirs"
        ls
        for DIR in win-x64 linux-x64 osx-x64
        do
          cd $DIR/publish
          rm -r -f cs
          rm -r -f de
          rm -r -f es
          rm -r -f fr
          rm -r -f it
          rm -r -f ja
          rm -r -f ko
          rm -r -f pl
          rm -r -f pt-BR
          rm -r -f ru
          rm -r -f tr
          rm -r -f zh-Hans
          rm -r -f zh-Hant
          cd ..
        done
        
        echo "Preparing Linux build"

        echo "Preparing Portable build"
        
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Rysy-windows
        path: Rysy/bin/Release/net7.0/win-x64/publish

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Rysy-linux
        path: Rysy/bin/Release/net7.0/linux-x64/publish

    - name: Upload OSX artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Rysy-osx
        path: Rysy/bin/Release/net7.0/osx-x64/publish
