using ImGuiNET;
using Rysy.Extensions;
using Rysy.Helpers;
using Rysy.History;

namespace Rysy.Gui.Windows;

public sealed class MetadataWindow : Window {
    private static FieldList AddTooltips(FieldList fields) {
        foreach (var (name, field) in fields) {
            field.Tooltip ??= name.TranslateOrNull("rysy.metadata.field.description");
            field.NameOverride ??= name.TranslateOrNull("rysy.metadata.field.name");
        }

        return fields;
    }

    public static FieldList GetMainFieldInfo(MapMetadata map) => AddTooltips(new() {
        ["AnimatedTiles"] = Fields.String(map.AnimatedTiles).AllowNull(),
        ["BackgroundTiles"] = Fields.String(map.BackgroundTiles).AllowNull(),
        ["BloomBase"] = Fields.Float(map.BloomBase ?? 0f),
        ["BloomStrength"] = Fields.Float(map.BloomStrength ?? 1f),
        //["CassetteCheckpointIndex"] = Fields.Int(map.CassetteCheckpointIndex ?? 0), // auto-generated by Everest
        ["ColorGrade"] = Fields.String(map.ColorGrade).AllowNull(),
        ["CoreMode"] = Fields.String(map.CoreMode).AllowNull(), // todo: dropdown
        ["DarknessAlpha"] = Fields.Float(map.DarknessAlpha ?? 0.05f),
        ["Dreaming"] = Fields.Bool(map.Dreaming ?? false),
        ["ForegroundTiles"] = Fields.String(map.ForegroundTiles).AllowNull(),
        ["Icon"] = Fields.String(map.Icon).AllowNull(),
        ["Interlude"] = Fields.Bool(map.Interlude ?? false),
        ["IntroType"] = Fields.EnumNamesDropdown<IntroTypes>(map.IntroType).AllowNull(),
        ["Portraits"] = Fields.String(map.Portraits).AllowNull(),
        ["PostcardSoundID"] = Fields.String(map.PostcardSoundID).AllowNull(),
        ["Sprites"] = Fields.String(map.Sprites).AllowNull(),
        ["TitleAccentColor"] = Fields.RGB((map.TitleAccentColor ?? "2f344b").FromRGB()),
        ["TitleBaseColor"] = Fields.RGB((map.TitleBaseColor ?? "6c7c81").FromRGB()),
        ["TitleTextColor"] = Fields.RGB((map.TitleTextColor ?? "ffffff").FromRGB()),
        ["Wipe"] = Fields.String(map.Wipe).AllowNull(), // todo: dropdown
    });

    public static FieldList GetModeFieldInfo(MapMetadata map) => AddTooltips(new() {
        ["OverrideASideMeta"] = Fields.Bool(map.OverrideASideMeta ?? false),
        ["mode:HeartIsEnd"] = Fields.Bool(map.Mode.HeartIsEnd ?? false),
        ["mode:Inventory"] = Fields.EnumNamesDropdown<Inventories>(map.Mode.Inventory).AllowNull(),
        //["mode:PoemID"] = Fields.String(map.Mode.PoemID).AllowNull(),
        ["mode:SeekerSlowdown"] = Fields.Bool(map.Mode.SeekerSlowdown ?? false),
        ["mode:StartLevel"] = Fields.String(map.Mode.StartLevel).AllowNull(),
        ["mode:TheoInBubble"] = Fields.Bool(map.Mode.TheoInBubble ?? false),
    });

    public static FieldList GetCassetteFieldInfo(MapMetadata map) => AddTooltips(new() {
        ["CassetteSong"] = Fields.String(map.CassetteSong).AllowNull(),
        ["cassettemodifier:BeatIndexOffset"] = Fields.Int(map.CassetteModifier.BeatIndexOffset),
        ["cassettemodifier:BeatsMax"] = Fields.Int(map.CassetteModifier.BeatsMax),
        ["cassettemodifier:BeatsPerTick"] = Fields.Int(map.CassetteModifier.BeatsPerTick),
        ["cassettemodifier:Blocks"] = Fields.Int(map.CassetteModifier.Blocks),
        ["cassettemodifier:LeadBeats"] = Fields.Int(map.CassetteModifier.LeadBeats),
        ["cassettemodifier:OldBehavior"] = Fields.Bool(map.CassetteModifier.OldBehavior),
        ["cassettemodifier:TempoMult"] = Fields.Float(map.CassetteModifier.TempoMult),
        ["cassettemodifier:TicksPerSwap"] = Fields.Int(map.CassetteModifier.TicksPerSwap),
    });

    public static FieldList GetMusicFieldInfo(MapMetadata map) => AddTooltips(new() {
        ["mode:audiostate:Music"] = Fields.Dropdown(map.Mode.AudioState.Music, CelesteEnums.Music).AllowNull().AllowEdits(),
        ["mode:audiostate:Ambience"] = Fields.String(map.Mode.AudioState.Ambience).AllowNull(), // todo: dropdown
    });

    public HistoryHandler History { get; private set; }
    public Map Map { get; private set; }

    private List<(string Name, FormWindow Window)> Tabs = new();

    public MetadataWindow(HistoryHandler history, Map map) : base("Map Metadata", new(800, 400)) {
        Map = map;
        History = history;

        Tabs.Add(("Main", new(GetMainFieldInfo(map.Meta), "##main") {
            OnChanged = ApplyChanges
        }));
        Tabs.Add(("Mode", new(GetModeFieldInfo(map.Meta), "##mode") {
            OnChanged = ApplyChanges
        }));
        Tabs.Add(("Cassette", new(GetCassetteFieldInfo(map.Meta), "##cass") {
            OnChanged = ApplyChanges
        }));
        Tabs.Add(("Music", new(GetMusicFieldInfo(map.Meta), "##music") {
            OnChanged = ApplyChanges
        }));

        NoSaveData = false;
    }

    private void ApplyChanges(Dictionary<string, object> edited) {
        var map = Map;

        var oldMetaPacked = map.Meta.Pack();
        foreach (var (name, val) in edited) {
            var nameSplit = name.Split(':');
            var (innerchild, child, fieldName) = nameSplit.Length switch {
                1 => (null, null, nameSplit[0]),
                2 => (null, nameSplit[0], nameSplit[1]),
                3 => (nameSplit[1], nameSplit[0], nameSplit[2]),
                _ => throw new NotImplementedException()
            };

            var el = child is null ? oldMetaPacked : oldMetaPacked.Children.First(c => c.Name == child);
            if (innerchild is { })
                el = el.Children.First(c => c.Name == innerchild);

            el.Attributes[fieldName] = val;
        }

        var newMeta = new MapMetadata().Unpack(oldMetaPacked);

        History.ApplyNewAction(new MapMetaEditAction(map, newMeta));
    }

    protected override void Render() {
        base.Render();

        if (ImGui.BeginTabBar("Tabbar")) {
            foreach (var tab in Tabs) {
                if (ImGui.BeginTabItem(tab.Name)) {
                    tab.Window.RenderBody();
                    ImGui.EndTabItem();
                }
            }

            ImGui.EndTabBar();
        }
    }
}
